name = "stl-fortran"
author = "Jacob Williams"
copyright  = "Copyright (c) 2020-2022, Jacob Williams"
license = "BSD-3"
description = "Fortran STL File I/O"
homepage = "https://github.com/jacobwilliams/stl-fortran"
keywords = ["STL"]

[build]
auto-executables = false
auto-examples = false
auto-tests = true
link = ["lapack", "blas"]

[library]
source-dir = "src"

[install]
library = true