add_axes – stl-fortran
add_axes Subroutine
15 statements
Source File
private subroutine add_axes(me, origin, vx, vy, vz, radius, num_points, arrowhead_radius_factor, arrowhead_length_factor)
Add x,y,z axes to an STL file.
Type Bound
stl_file
Arguments
Type Intent Optional Attributes Name
class(stl_file), intent(inout) :: me
real(kind=wp), intent(in), dimension(3) :: origin
coordinates of the origin of the axes
real(kind=wp), intent(in), dimension(3) :: vx
x axis vector
real(kind=wp), intent(in), dimension(3) :: vy
y axis vector
real(kind=wp), intent(in), dimension(3) :: vz
z axis vector
real(kind=wp), intent(in) :: radius
radius of the cylinder
integer, intent(in) :: num_points
number of point on the circle (>=3)
real(kind=wp), intent(in) :: arrowhead_radius_factor
arrowhead cone radius factor (multiple of cylinder radius)
real(kind=wp), intent(in) :: arrowhead_length_factor
arrowhead tip length factor (multiple of vector length)
Calls
Source Code
    subroutine add_axes(me,origin,vx,vy,vz,radius,num_points,&
                        arrowhead_radius_factor,arrowhead_length_factor)
    implicit none
    class(stl_file),intent(inout)    :: me
    real(wp),dimension(3),intent(in) :: origin                  !! coordinates of the origin of the axes
    real(wp),dimension(3),intent(in) :: vx                      !! x axis vector
    real(wp),dimension(3),intent(in) :: vy                      !! y axis vector
    real(wp),dimension(3),intent(in) :: vz                      !! z axis vector
    real(wp),intent(in)              :: radius                  !! radius of the cylinder
    integer,intent(in)               :: num_points              !! number of point on the circle (>=3)
    real(wp),intent(in)              :: arrowhead_radius_factor !! arrowhead cone radius factor
                                                                !! (multiple of cylinder radius)
    real(wp),intent(in)              :: arrowhead_length_factor !! arrowhead tip length factor
                                                                !! (multiple of vector length)
    call me%add_arrow(origin,vx,radius,num_points,arrowhead_radius_factor,arrowhead_length_factor)
    call me%add_arrow(origin,vy,radius,num_points,arrowhead_radius_factor,arrowhead_length_factor)
    call me%add_arrow(origin,vz,radius,num_points,arrowhead_radius_factor,arrowhead_length_factor)
    end subroutine add_axes
Call graph
add_axes calls add_arrow
add_arrow calls add_cone, add_cylinder
add_cone calls add_plate, generate_circle, unit
add_cylinder calls add_plate, generate_circle, unit
generate_circle calls add_plate, unit, axis_angle_rotation, perpendicular, vector_projection_on_plane
axis_angle_rotation calls unit, cross
perpendicular calls unit
vector_projection_on_plane calls vector_projection