add_plate – stl-fortran
add_plate Subroutine
29 statements
Source File
private subroutine add_plate(me, v1, v2, v3)
Add a plate to the class.
Type Bound
stl_file
Arguments
Type Intent Optional Attributes Name
class(stl_file), intent(inout) :: me
real(kind=wp), intent(in), dimension(3) :: v1
first vertex
real(kind=wp), intent(in), dimension(3) :: v2
second vertex
real(kind=wp), intent(in), dimension(3) :: v3
third vertex
Called by
Source Code
    subroutine add_plate(me,v1,v2,v3)
    class(stl_file),intent(inout)    :: me
    real(wp),dimension(3),intent(in) :: v1 !! first vertex
    real(wp),dimension(3),intent(in) :: v2 !! second vertex
    real(wp),dimension(3),intent(in) :: v3 !! third vertex
    integer :: n !! actual size of `plates` array in the class
    type(plate),dimension(:),allocatable :: tmp !! for resizing the `plates` array
    if (allocated(me%plates)) then
        n = size(me%plates)
        if (me%n_plates == n) then
            ! have to add another chunk
            allocate(tmp(n+me%chunk_size))
            tmp(1:n) = me%plates
            tmp(n+1)%v1 = v1
            tmp(n+1)%v2 = v2
            tmp(n+1)%v3 = v3
            call move_alloc(tmp,me%plates)
            me%n_plates = me%n_plates + 1
            return
        else
            ! add to next element in the class
            me%n_plates = me%n_plates + 1
        end if
    else
        allocate(me%plates(me%chunk_size))
        me%n_plates = 1
    end if
    me%plates(me%n_plates)%v1 = v1
    me%plates(me%n_plates)%v2 = v2
    me%plates(me%n_plates)%v3 = v3
    end subroutine add_plate
Call graph
add_cone calls add_plate, generate_circle
add_cylinder calls add_plate, generate_circle
add_sphere calls add_plate
generate_circle calls add_plate
add_arrow calls add_cone, add_cylinder
add_curve calls add_cylinder
add_axes calls add_arrow