add_arrow – stl-fortran
add_arrow Subroutine
12 statements
Source File
private subroutine add_arrow(me, origin, v, radius, num_points, arrowhead_radius_factor, arrowhead_length_factor)
Add an arrow to an STL file.
Type Bound
stl_file
Arguments
Type Intent Optional Attributes Name
class(stl_file), intent(inout) :: me
real(kind=wp), intent(in), dimension(3) :: origin
coordinates of the origin of the axes
real(kind=wp), intent(in), dimension(3) :: v
vector
real(kind=wp), intent(in) :: radius
radius of the cylinder
integer, intent(in) :: num_points
number of point on the circle (>=3)
real(kind=wp), intent(in) :: arrowhead_radius_factor
arrowhead cone radius factor (multiple of cylinder radius)
real(kind=wp), intent(in) :: arrowhead_length_factor
arrowhead tip length factor (multiple of vector length)
Calls
Called by
Source Code
    subroutine add_arrow(me,origin,v,radius,num_points,&
                         arrowhead_radius_factor,arrowhead_length_factor)
    implicit none
    class(stl_file),intent(inout)    :: me
    real(wp),dimension(3),intent(in) :: origin                   !! coordinates of the origin of the axes
    real(wp),dimension(3),intent(in) :: v                        !! vector
    real(wp),intent(in)              :: radius                   !! radius of the cylinder
    integer,intent(in)               :: num_points               !! number of point on the circle (>=3)
    real(wp),intent(in)              :: arrowhead_radius_factor  !! arrowhead cone radius factor
                                                                 !! (multiple of cylinder radius)
    real(wp),intent(in)              :: arrowhead_length_factor  !! arrowhead tip length factor
                                                                 !! (multiple of vector length)
    call me%add_cylinder(origin,v,radius,num_points,&
                         initial_cap=.true.,final_cap=.true.)
    call me%add_cone(v,v+arrowhead_length_factor*v,&
                     arrowhead_radius_factor*radius,num_points,initial_cap=.true.)
    end subroutine add_arrow
Call graph
add_arrow calls add_cone, add_cylinder
add_cone calls add_plate, generate_circle, unit
add_cylinder calls add_plate, generate_circle, unit
generate_circle calls add_plate, unit, axis_angle_rotation, perpendicular, vector_projection_on_plane
axis_angle_rotation calls unit, cross
perpendicular calls unit
vector_projection_on_plane calls vector_projection
add_axes calls add_arrow