axis_angle_rotation – stl-fortran
axis_angle_rotation Function
Jacob Williams
7/20/2014
13 statements
Source File
private pure function axis_angle_rotation(v, k, theta) result(vrot)
Rotate a 3x1 vector in space, given an axis and angle of rotation.
Reference
Wikipedia
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3) :: v
vector to rotate
real(kind=wp), intent(in), dimension(3) :: k
rotation axis
real(kind=wp), intent(in) :: theta
rotation angle [deg]
Return Value real(kind=wp), dimension(3)
result
Calls
Called by
Source Code
    pure function axis_angle_rotation(v,k,theta) result(vrot)
    implicit none
    real(wp),dimension(3),intent(in)  :: v      !! vector to rotate
    real(wp),dimension(3),intent(in)  :: k      !! rotation axis
    real(wp),intent(in)               :: theta  !! rotation angle [deg]
    real(wp),dimension(3)             :: vrot   !! result
    real(wp),dimension(3) :: khat
    real(wp) :: ct,st
    ct = cos(theta*deg2rad)
    st = sin(theta*deg2rad)
    khat = unit(k)   !rotation axis unit vector
    vrot = v*ct + cross(khat,v)*st + khat*dot_product(khat,v)*(one-ct)
    end function axis_angle_rotation
Call graph
axis_angle_rotation calls cross, unit
generate_circle calls axis_angle_rotation
add_cone calls generate_circle
add_cylinder calls generate_circle
add_arrow calls add_cone, add_cylinder
add_curve calls add_cylinder
add_axes calls add_arrow