cross – stl-fortran
cross Function
9 statements
Source File
private pure function cross(a, b) result(axb)
Vector cross product.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3) :: a
real(kind=wp), intent(in), dimension(3) :: b
Return Value real(kind=wp), dimension(3)
Called by
Source Code
    pure function cross(a,b) result(axb)
    implicit none
    real(wp),dimension(3) :: axb
    real(wp),dimension(3),intent(in) :: a
    real(wp),dimension(3),intent(in) :: b
    axb(1) = a(2)*b(3) - a(3)*b(2)
    axb(2) = a(3)*b(1) - a(1)*b(3)
    axb(3) = a(1)*b(2) - a(2)*b(1)
    end function cross
Call graph
axis_angle_rotation calls cross
normal calls cross
generate_circle calls axis_angle_rotation
write_ascii_stl_file calls normal
write_binary_stl_file calls normal
add_cone calls generate_circle
add_cylinder calls generate_circle
add_arrow calls add_cone, add_cylinder
add_curve calls add_cylinder
add_axes calls add_arrow