perpendicular – stl-fortran
perpendicular Function
8 statements
Source File
private pure function perpendicular(v1, v2) result(is_parallel)
Returns true if the two vectors are perpendicular.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: v1
real(kind=wp), intent(in), dimension(:) :: v2
Return Value logical
Calls
Called by
Source Code
    pure function perpendicular(v1, v2) result(is_parallel)
    implicit none
    real(wp),dimension(:),intent(in) :: v1
    real(wp),dimension(:),intent(in) :: v2
    logical :: is_parallel
    real(wp),parameter :: tol = 10.0_wp * epsilon(1.0_wp) !! tolerance
    is_parallel = abs(dot_product(unit(v1), unit(v2))) <= tol
    end function perpendicular
Call graph
perpendicular calls unit
generate_circle calls perpendicular
add_cone calls generate_circle
add_cylinder calls generate_circle
add_arrow calls add_cone, add_cylinder
add_curve calls add_cylinder
add_axes calls add_arrow