unit – stl-fortran
unit Function
12 statements
Source File
private pure function unit(r) result(rhat)
3x1 Unit vector.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3) :: r
Return Value real(kind=wp), dimension(3)
Called by
Source Code
    pure function unit(r) result(rhat)
    implicit none
    real(wp),dimension(3)            :: rhat
    real(wp),dimension(3),intent(in) :: r
    real(wp) :: rmag
    rmag = norm2(r)
    if (rmag/=zero) then
        rhat = r/rmag
    else
        rhat = zero
    end if
    end function unit
Call graph
add_cone calls unit, generate_circle
add_curve calls unit, add_cylinder
add_cylinder calls unit, generate_circle
axis_angle_rotation calls unit
generate_circle calls unit, axis_angle_rotation, perpendicular
normal calls unit
perpendicular calls unit
add_arrow calls add_cone, add_cylinder
write_ascii_stl_file calls normal
write_binary_stl_file calls normal
add_axes calls add_arrow