vector_projection – stl-fortran
vector_projection Function
13 statements
Source File
private pure function vector_projection(a, b) result(c)
The projection of one vector onto another vector.
Reference
Wikipedia
History
Jacob Williams : 7/21/2014
JW : fixed a typo : 6/18/2021
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: a
the original vector
real(kind=wp), intent(in), dimension(size(a)) :: b
the vector to project on to
Return Value real(kind=wp), dimension(size(a))
the projection of a onto b
Called by
Source Code
    pure function vector_projection(a,b) result(c)
    implicit none
    real(wp),dimension(:),intent(in)       :: a  !! the original vector
    real(wp),dimension(size(a)),intent(in) :: b  !! the vector to project on to
    real(wp),dimension(size(a))            :: c  !! the projection of a onto b
    real(wp) :: bmag2
    bmag2 = dot_product(b,b)
    if (bmag2==zero) then
        c = zero
    else
        c = b * dot_product(a,b) / bmag2
    end if
    end function vector_projection
Call graph
vector_projection_on_plane calls vector_projection
generate_circle calls vector_projection_on_plane
add_cone calls generate_circle
add_cylinder calls generate_circle
add_arrow calls add_cone, add_cylinder
add_curve calls add_cylinder
add_axes calls add_arrow